### PR TITLE
pem: error for sections that are too large

### LINKED ISSUE #105: Memory Leak: from_buf should fail fast with an error when the input is not valid PEM data
The bug: rustls_pki_types::pem::from_buf enters a pathological allocation pattern (~230 MB/s in release mode) when the CA certificate path points to a directory instead of a valid PEM file. Instead of returning an error quickly, it leaks memory unboundedly.                                                                                          
                                                                                                                      
What should happen: from_buf should fail fast with an error when the input is not valid PEM data (e.g., empty, binary garbage, or a directory read result).                                                                        
                                                                                                                        
Reproduction:                                                                                                       
- Mount an empty directory as /etc/ssl/certs/ca-certificates.crt                                                    
- Use reqwest with rustls backend to make HTTPS requests
- Memory grows at ~230 MB/s until OOM kill

Affected version: rustls-pki-types v1.12.0

DHAT evidence: The top allocation site is rustls_pki_types::pem::from_buf at lines 228 and 230 of pem.rs, allocating 290 MB in 10 seconds through Vec::with_capacity(1024) in a loop.

### PR DESCRIPTION
**Pull request by djc**
Fixes #105.

First thought 64 kB might be enough (see also rustls' `CERTIFICATE_MAX_SIZE_LIMIT`), but I think CRLs might be a good chunk larger for large CAs, so maybe start with 10 MB?

```rust
/// A single recognised section in a PEM file.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum SectionKind {
    /// A DER-encoded x509 certificate.
    ///
    /// Appears as "CERTIFICATE" in PEM files.
    Certificate,

    /// A DER-encoded Subject Public Key Info; as specified in RFC 7468.
    ///
    /// Appears as "PUBLIC KEY" in PEM files.
    PublicKey,

    /// A DER-encoded plaintext RSA private key; as specified in PKCS #1/RFC 3447
    ///
    /// Appears as "RSA PRIVATE KEY" in PEM files.
    RsaPrivateKey,

    /// A DER-encoded plaintext private key; as specified in PKCS #8/RFC 5958
    ///
    /// Appears as "PRIVATE KEY" in PEM files.
    PrivateKey,

    /// A Sec1-encoded plaintext private key; as specified in RFC 5915
    ///
    /// Appears as "EC PRIVATE KEY" in PEM files.
    EcPrivateKey,

    /// A Certificate Revocation List; as specified in RFC 5280
    ///
    /// Appears as "X509 CRL" in PEM files.
    Crl,

    /// A Certificate Signing Request; as specified in RFC 2986
    ///
    /// Appears as "CERTIFICATE REQUEST" in PEM files.
    Csr,

    /// An EchConfigList structure, as specified in
    /// <https://www.ietf.org/archive/id/draft-farrell-tls-pemesni-05.html>.
    ///
    /// Appears as "ECHCONFIG" in PEM files.
    EchConfigList,
}
```

### CODE REVIEW

**Comment by ctz** [comment]
Sorry for delay on this one. Here's a list of CRLs for public issuers (top 20, DER-encoded):

```
12759372	out/371a00dc/DigiCertG5TLSRSA4096SHA3842021CA1-1.crl
10935863	out/9a6ec012/accvca120_der.crl
9141514	out/cb3ccbb7/DigiCertGlobalG2TLSRSASHA2562020CA1-1.crl
2364354	out/49e7a442/d-trust_ssl_class_3_ca_1_2009.der.crl
2364354	out/49e7a442/d-trust_ssl_class_3_ca_1_2009.crl
731650	out/f1c1b50a/SSL.com-TLS-I-RSA-R1.crl
731650	out/97552015/SSL.com-TLS-I-RSA-R1.crl
731650	out/4200f504/SSL.com-TLS-I-RSA-R1.crl
664167	out/c32ffd9f/SSL.com-TLS-I-ECC-R2.crl
664167	out/945bbc82/SSL.com-TLS-I-ECC-R2.crl
664167	out/55903859/SSL.com-TLS-I-ECC-R2.crl
345026	out/85666a56/SSLcom-SubCA-SSL-RSA-4096-R1.crl
310304	out/d947432a/85QyHZnkuAw.crl
245048	out/e3b6a2db/servicesca.crl
245048	out/d48d3d23/servicesca.crl
205058	out/96bcec06/19.crl
94249	out/7bb647a6/SectigoPublicServerAuthenticationCAEVR36.crl
93350	out/eec5496b/d-trust_ssl_class_3_ca_1_ev_2009.der.crl
93350	out/eec5496b/d-trust_ssl_class_3_ca_1_ev_2009.crl
```

So a 10MB limit would be inappropriate. I suggest 64MB as a start?

**Comment by djc** [comment]
Bumped the limit to 64 MB.

File: src/pem.rs [hunk 1]
```diff
@@ -493,6 +498,9 @@ pub enum Error {
 
     /// No items found of desired type
     NoItemsFound,
+
+    /// PEM section exceeds maximum allowed size of 10 MB
```
Comment (ctz) [inline src/pem.rs]:
```suggestion
    /// PEM section exceeds maximum allowed size of 64 MB
```

**Review by ctz — APPROVED** [review]

File: src/pem.rs (hunk 1 above)
Comment (djc) [reply src/pem.rs]: Nice catch!
